DROP PROCEDURE AddMinifig;
DROP PROCEDURE AddInventoryItem;
DROP PROCEDURE AddSet;
DROP PROCEDURE AddElement;
DROP PROCEDURE ColorlessInventory;
DROP PROCEDURE InSets;

DROP TABLE Inventory;
DROP TABLE MinifigInventory;
DROP TABLE Element;
DROP TABLE Minifigure;
DROP TABLE Design;
DROP TABLE Color;
DROP TABLE LegoSet;
DROP TABLE Theme;